K-평균 군집화(K-means Clustering) 모델

데이터 안에서 대표하는 군집의 중심을 찾는 알고리즘

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

from sklearn.model_selection import train_test_split
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size=0.25, random_state=42)

In [ ]:
iris_dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)
# 군집 3개
k_means.fit(train_input)
KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
k_means.labels_

array([1, 1, 2, 2, 2, 1, 1, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 2, 1, 1, 1, 2,
       2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       1, 2, 0, 1, 2, 1, 1, 2, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1, 1, 2,
       0, 1, 0, 0, 1, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2,
       0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 0], dtype=int32)

In [ ]:
print("0 cluster:", train_label[k_means.labels_ ==0])
print("1 cluster:", train_label[k_means.labels_ ==1])
print("2 cluster:", train_label[k_means.labels_ ==2])

0 cluster: [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]
1 cluster: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 cluster: [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]


k-평균 군집화 모델 알고리즘 특성상 실행때마다 결과가 다르게 나온다.(순서만 다름)

즉, 각 군집이 어떤 라벨을 의미하는지만 파악하면 된다.

In [ ]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

prediction = k_means.predict(new_input)
prediction
# 예측 결과가 2번째 군집인것을 알 수 있다

array([2], dtype=int32)

In [ ]:
# 실제 모델의 정확도 평가
predict_cluster= k_means.predict(test_input)
predict_cluster

array([2, 1, 0, 2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 0, 2, 2, 0, 1, 2,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1], dtype=int32)

In [ ]:
# 실제 Label로 재정의
actual_label = np.array(predict_cluster)
actual_label[actual_label==0],actual_label[actual_label==1],actual_label[actual_label==2] = 3,4,5
actual_label[actual_label==5] =1
actual_label[actual_label==4] =0
actual_label[actual_label==3] =2

predict_label = actual_label.tolist()
print(predict_label)


[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]


In [ ]:
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 0.95
