# 벡터와 행렬 연산


소프트맥스 회귀에서는 종속 변수 y의 종류가 3개 이상이 되면서 복잡해지고, 이를 누적하여 인공 신경망이 생긴다.
- 사용 데이터와 변수의 개수로부터 행렬의 크기, 텐서의 크기를 산정할 수 있어야 한다

## 1. 벡터와 행렬과 텐서
- 벡터는 크기와 방향을 가진 양
    - 숫자가 나열된 형상, 파이썬에서는 1차원 배열 또는 리스트로 표현한다
- 행렬은 행과 열을 가지는 2차원 형상을 가진 구조
    - 파이썬에서는 2차원 배열로 표현
    - 가로(row), 세로(column)
- 텐서는 3차원

## 2. 텐서(Tensor)
- 인공 신경망의 복잡한 연산을 수행하는 것!

#### 1) 0차원 텐서(스칼라)
- 스칼라는 하나의 실수값으로 이루어진 데이터
- 0D Tensor

In [4]:
import numpy as np
d = np.array(5)
print(" 텐서의 차원 : ", d.ndim)
print(" 텐서의 크기(shape) :", d.shape)

 텐서의 차원 :  0
 텐서의 크기(shape) : ()


#### 2) 1차원 텐서(벡터)
- 숫자를 배열한 것
- 벡터의 차원과 텐서의 차원은 다름
    - 벡터의 차원은 하나의 축에 놓인 원소의 개수
    - 텐서의 차원은 축의 개수
- 아래 예제에서 4차원 벡터이지만, 1차원 텐서이다
- 1D Tensor

In [5]:
d = np.array([1,2,3,4])
print("텐서의 차원 : ", d.ndim)
print("텐서의 크기(shape) :", d.shape)


텐서의 차원 :  1
텐서의 크기(shape) : (4,)


#### 3) 2차원 텐서(행렬)
- 행과 열이 존재하는 벡터의 배열 -> 행렬(Matrix)
- 텐서의 크기 : 각 축을 따라 얼마나 많은 차원이 있는지 나타낸 값
- 2D Tensor

In [7]:
d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("텐서의 차원 : ", d.ndim)
print("텐서의 크기 :", d.shape)

텐서의 차원 :  2
텐서의 크기 : (3, 4)


#### 4) 3차원 텐서(다차원 배열)
- 행렬을 한번 더 배열하면 3차원 텐서
- 3D Tensor
- 시퀀스 데이터를 표현할 떄 자주 사용
    - 이때, 시퀀스는 단어의 시퀀스를 의미
    - 주로 문장이나 문서, 뉴스 기사 등의 텍스트가 될 수 있다.
    - 3D Tensor 
        - (samples, timesteps, word_dim)
        - (batch_size, timesteps, word_dim)
        


In [9]:
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


- 문서1 : I like NLP
- 문서2 : I like DL
- 문서3 : DL is AI

각 단어를 벡터화 해준다.

<table>
단어	One-hot vector<br>
I 	[1 0 0 0 0 0]<br>
like	[0 1 0 0 0 0]<br>
NLP	[0 0 1 0 0 0]<br>
DL	[0 0 0 1 0 0]<br>
is	[0 0 0 0 1 0]<br>
AI	[0 0 0 0 0 1]
</table>
- 위 훈련 데이터를 다수묶어 입력으로 사용하는 것 (batch)


[[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]],


[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]],


[[0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]]]


(3, 3, 6) 의 크기를 가지는 3D Tensor

#### 6) 케라스에서의 텐서
- input_shape = (batch_size, input_length, input_dim)

## 3. 벡터와 행렬의 연산

#### 1) 벡터와 행렬의 덧셈과 뺄셈

In [10]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A + B)
print('두 행렬의 차 :')
print(A - B)


두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


In [11]:
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합 :',A+B)
print('두 벡터의 차 :',A-B)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


#### 2) 벡터의 내적과 행렬의 곱셈

In [12]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :',np.dot(A, B))

두 벡터의 내적 : 32


In [13]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]
